name: Check

on:
  pull_request:
  push:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download binaries test
      run: |
          make binaries
